### ISSUE TITLE
Adding python version to CI

### ISSUE THREAD

**Issue by kallewesterling** [Living-with-machines/T-Res#244]
I wonder if there's a step missing in the `ci.yml` GitHub action file, where the cache setup is looking for `steps.full-python-version.outputs.version`, but there is nothing like `full-python-version` in the `steps`. I believe, after some googling, that this is the step that should be inserted after `Set up Python`:

```yml
- name: Get full Python version
    id: full-python-version
    run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
```

Alternatively, I think we can replace the `steps.full-python-version.outputs.version` with `matrix.python-version` as that's what we're running with here?
